##### 丢弃发的概念
对输入层或隐含层做如下操作：

- 随机选择一部分改层的输出作为丢弃元素
- 把丢弃元素乘以0
- 把非丢弃元素拉伸

In [1]:
# 实现
from mxnet import nd

def dropout(X, drop_probability): #drop_probability 定义元素被丢弃的概率
    keep_probability = 1 - drop_probability
    assert 0 <= keep_probability <= 1
    #当概率为1时，将所有元素都丢弃
    if keep_probability == 0:
        return X.zeros_like()
    
    mask = nd.random.uniform(0, 1.0, X.shape, ctx=X.context) < keep_probability
    print('mask:', mask)
    scale = 1 / keep_probability
    print('scale:', scale)
    return mask * X * scale

In [2]:
A = nd.arange(20).reshape((5, 4))
dropout(A, 0.0)

mask: 
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 5x4 @cpu(0)>
scale: 1.0



[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>

In [3]:
dropout(A, 0.5)

mask: 
[[ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  1.  0.  0.]]
<NDArray 5x4 @cpu(0)>
scale: 2.0



[[  0.   0.   0.   6.]
 [  0.  10.   0.   0.]
 [ 16.  18.  20.   0.]
 [ 24.  26.   0.   0.]
 [  0.  34.   0.   0.]]
<NDArray 5x4 @cpu(0)>

In [4]:
dropout(A, 1.0)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>