In [1]:
from mxnet import ndarray as nd

创建3行4列的数组

In [2]:
nd.zeros((3,4))


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

初始化一个所有元素为1的3行4列数组

In [3]:
x = nd.ones((3, 4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

从python中数组构造

In [5]:
nd.array([[1,2], [2,3]])


[[ 1.  2.]
 [ 2.  3.]]
<NDArray 2x2 @cpu(0)>

创建随机数组

In [6]:
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[ 2.21220636  0.7740038   1.04344046  1.18392551]
 [ 1.89171135 -1.23474145 -1.771029   -0.45138445]
 [ 0.57938355 -1.85608196 -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [7]:
y.shape

(3, 4)

In [8]:
y.size

12

In [9]:
x * y


[[ 2.21220636  0.7740038   1.04344046  1.18392551]
 [ 1.89171135 -1.23474145 -1.771029   -0.45138445]
 [ 0.57938355 -1.85608196 -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.exp(y)


[[ 9.13585091  2.16843081  2.83896756  3.26717448]
 [ 6.63070631  0.29090998  0.17015781  0.63674599]
 [ 1.78493774  0.15628375  0.13850074  0.81219143]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.dot(x, y.T)


[[ 5.21357632 -1.56544352 -3.4615972 ]
 [ 5.21357632 -1.56544352 -3.4615972 ]
 [ 5.21357632 -1.56544352 -3.4615972 ]]
<NDArray 3x3 @cpu(0)>

In [12]:
a = nd.arange(3).reshape((3, 1))
b = nd.arange(2).reshape((1, 2))
print('a:', a)
print('b:', b)
print('a + b:', a + b)

a: 
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
b: 
[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>
a + b: 
[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>


***与Numpy转换***

In [14]:
import numpy as np
x = np.ones((2, 3))
y = nd.array(x) #numpy -> mxnet
z = y.asnumpy() #mxnet -> numpy
print([z, y])

[array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32), 
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>]


替换操作

In [20]:
x = nd.ones((3, 4))
y = nd.ones((3, 4))

before = id(y)
y = y + x
print(id(y) == before)

False


[:] 使用

In [25]:
z = nd.zeros_like(x)
before = id(z)
z[:] = x + y
id(z) == before

True

上面的操作创建了x + y 的临时空间再复制到z。避免这个开销可以使用操作符的全名版本的out参数

In [24]:
nd.elemwise_add(x, y, out=z)
id(z) == before

True

截取（Slicing）

In [26]:
x = nd.arange(0, 9).reshape((3, 3))
print('x:', x)
x[1:3]

x: 
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>



[[ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 2x3 @cpu(0)>

In [30]:
x[1, 2] = 9.0
print('x:', x)

x: 
[[ 0.  1.  2.]
 [ 3.  4.  9.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>


多维截取

In [29]:
x = nd.arange(0, 9).reshape((3, 3))
print('x', x)
x[1:2, 1:3]

x 
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>



[[ 4.  5.]]
<NDArray 1x2 @cpu(0)>

多维写入

In [31]:
x[1:2, 1:3] = 9.0
x


[[ 0.  1.  2.]
 [ 3.  9.  9.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>