In [4]:
import numpy as np

In [6]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <http://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <http://ipython.scipy.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particu

In [8]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
a.shape #ndarray的大小

(3, 5)

In [16]:
a.ndim #维度

2

In [14]:
a.dtype.name

'int64'

In [15]:
a.itemsize #ndarray 中每个元素的字节大小

8

In [17]:
a.size # ndarray 的元素个数

15

In [18]:
type(a)

numpy.ndarray

In [19]:
b = array([6, 7, 8])
b

array([6, 7, 8])

In [24]:
type(b)

numpy.ndarray

多维数组,初始化多个数据

In [25]:
a = array([(1, 2), (3, 4)])
a

array([[1, 2],
       [3, 4]])

指定创建的ndarray类型

In [22]:
c = array([[1, 2], [3, 4]], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

ndarray 初始化

In [26]:
zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [27]:
ones((2, 3, 4), dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [29]:
empty((2, 3)) # 创建一个随机数的ndarray

array([[  0.00000000e+000,   5.39494389e-317,   5.31021756e-317],
       [  6.90542634e-310,  -1.76692351e-286,   3.30146360e-258]])

In [30]:
arange(10, 30, 5)

array([10, 15, 20, 25])

In [31]:
arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [33]:
linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [35]:
x = linspace(0, 2 * pi, 100)
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [37]:
f = sin(x)
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [38]:
a = arange(6)
print(a)

[0 1 2 3 4 5]


In [39]:
b = arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
c = arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
print(arange(10000))

[   0    1    2 ..., 9997 9998 9999]


ndarray 数学操作

In [46]:
a = array([20, 30, 40, 50])
b = arange(4)
b
c = a - b
c

array([20, 29, 38, 47])

In [47]:
b ** 2

array([0, 1, 4, 9])

In [48]:
10 * sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [50]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [52]:
A = arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [53]:
A = array([[1, 1], [0, 1]])
B = array([[2, 0], [3, 4]])

In [54]:
A * B

array([[2, 0],
       [0, 4]])

In [55]:
dot(A, B) #不明白是个什么操作

array([[5, 4],
       [3, 4]])

In [64]:
a = ones((2, 3), dtype=int)
b = random.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [65]:
b += a
b

array([[ 3.80545379,  3.32266205,  3.77237132],
       [ 3.65211643,  3.43584743,  3.20195836]])

In [66]:
a = a + b
a

array([[ 6.80545379,  6.32266205,  6.77237132],
       [ 6.65211643,  6.43584743,  6.20195836]])

In [67]:
a = random.random((2, 3))
a

array([[ 0.25528497,  0.29243506,  0.23295683],
       [ 0.85690565,  0.12619448,  0.62111625]])

In [68]:
a.sum()

2.3848932360103157

In [69]:
a.min()

0.12619447522272342

In [70]:
a.max()

0.85690564788801782

In [71]:
b = arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
b.sum(axis=0) # 0 列

array([12, 15, 18, 21])

In [76]:
b.sum(axis=1) # 1 行

array([ 6, 22, 38])

In [77]:
b.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [73]:
b.min(axis=0)

array([0, 1, 2, 3])

In [74]:
b.min(axis=1)

array([0, 4, 8])

切割

In [79]:
a = arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [80]:
a[2]

8

In [81]:
a[2:5]

array([ 8, 27, 64])

In [82]:
a[:6:2] = -1000 # 从后往前 到倒数第六个开始，每隔两个数设置为-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [83]:
a[::-1] # 将 a 翻转（倒序）

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [85]:
for i in a:
    print(i ** (1 / 3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [86]:
def f(x, y):
    return 10 * x + y
b = fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [87]:
b[2, 3]

23

In [91]:
b[:1] # 获取第一行的数据

array([[0, 1, 2, 3]])

In [92]:
b[:, 1] # 在中间加了个逗号就完全不一样了！！！

array([ 1, 11, 21, 31, 41])

In [93]:
b[0:5, 1] # 拿到第1列的0-5行数据，与上面的操作相同

array([ 1, 11, 21, 31, 41])

In [95]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [100]:
b[1:3, 1:3]

array([12, 22])

In [101]:
b[1:3, -2]

array([12, 22])

In [102]:
b[-1]

array([40, 41, 42, 43])

In [104]:
c = array([[[0, 1, 2], [10, 12, 13]],
          [[100, 101, 102], [110, 112, 113]]])

In [105]:
c.shape

(2, 2, 3)

In [106]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [107]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [108]:
c[...]

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [109]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [112]:
for element in b.flat:
    print(element, end = " ")

0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43 

In [117]:
a = floor(10 * random.random((3, 4)))
a

array([[ 0.,  4.,  1.,  9.],
       [ 9.,  6.,  6.,  3.],
       [ 1.,  9.,  3.,  4.]])

In [123]:
a.shape

(3, 4)

In [124]:
a.ravel() # 压扁数组......

array([ 0.,  4.,  1.,  9.,  9.,  6.,  6.,  3.,  1.,  9.,  3.,  4.])

In [125]:
a.shape

(3, 4)

In [127]:
a.shape = (6, 2)
a

array([[ 0.,  4.],
       [ 1.,  9.],
       [ 9.,  6.],
       [ 6.,  3.],
       [ 1.,  9.],
       [ 3.,  4.]])

In [128]:
a.transpose() # 矩阵转置

array([[ 0.,  1.,  9.,  6.,  1.,  3.],
       [ 4.,  9.,  6.,  3.,  9.,  4.]])

In [129]:
a

array([[ 0.,  4.],
       [ 1.,  9.],
       [ 9.,  6.],
       [ 6.,  3.],
       [ 1.,  9.],
       [ 3.,  4.]])

In [131]:
a.resize((2, 6))
a

array([[ 0.,  4.,  1.,  9.,  9.,  6.],
       [ 6.,  3.,  1.,  9.,  3.,  4.]])

In [132]:
a.reshape(3, -1)

array([[ 0.,  4.,  1.,  9.],
       [ 9.,  6.,  6.,  3.],
       [ 1.,  9.,  3.,  4.]])

In [133]:
a = floor(10 * random.random((2, 2)))
a

array([[ 4.,  7.],
       [ 0.,  8.]])

In [145]:
b = floor(10 * random.random((2, 2)))
b

array([[ 7.,  1.],
       [ 3.,  4.]])

vstack,hstack

In [143]:
c = vstack((a, b))
c

array([[ 4.,  7.],
       [ 0.,  8.],
       [ 7.,  7.],
       [ 6.,  0.]])

In [144]:
c.shape

(4, 2)

In [142]:
d = hstack((a, b))
d

array([[ 4.,  7.,  7.,  7.],
       [ 0.,  8.,  6.,  0.]])

In [140]:
d.shape

(2, 4)

hsplit

In [146]:
a = floor(10 * random.random((2, 12)))
a

array([[ 9.,  2.,  7.,  7.,  4.,  3.,  3.,  1.,  9.,  6.,  3.,  7.],
       [ 0.,  1.,  6.,  6.,  1.,  7.,  0.,  5.,  5.,  6.,  3.,  8.]])

In [147]:
hsplit(a, 3) # 将 a 拆分成 3 份

[array([[ 9.,  2.,  7.,  7.],
        [ 0.,  1.,  6.,  6.]]), array([[ 4.,  3.,  3.,  1.],
        [ 1.,  7.,  0.,  5.]]), array([[ 9.,  6.,  3.,  7.],
        [ 5.,  6.,  3.,  8.]])]

In [148]:
hsplit(a, (3, 4)) # 将 a 在 3,4列分拆开

[array([[ 9.,  2.,  7.],
        [ 0.,  1.,  6.]]), array([[ 7.],
        [ 6.]]), array([[ 4.,  3.,  3.,  1.,  9.,  6.,  3.,  7.],
        [ 1.,  7.,  0.,  5.,  5.,  6.,  3.,  8.]])]

In [154]:
id(a) #id 表示Python对象，唯一性

139767360059952

In [165]:
a = arange(12)
b = a
c = a.view()

In [167]:
b is a

True

In [168]:
c is a

False

In [170]:
c.base is a

True

In [171]:
c.shape

(12,)

In [173]:
c.shape = 2, 6
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [174]:
a.shape

(12,)

In [175]:
c[0, 4] = 1234
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [185]:
a

array([   0,    1,    2,    3, 1234,    5,    6,    7,    8,    9,   10,
         11])

In [186]:
a.shape = 2, 6

In [187]:
d = a.copy()
d is a

False

In [188]:
d.base is a

False

In [189]:
d

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [190]:
d[0, 0] = 999
a

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])