读写NDArrays

In [2]:
from mxnet import nd
from mxnet.gluon import nn

x = nd.ones(3)
y = nd.zeros(4)
filename = '../data/test1.params'
nd.save(filename, [x, y])

In [3]:
a, b = nd.load(filename)
print(a, b)


[ 1.  1.  1.]
<NDArray 3 @cpu(0)> 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>


In [4]:
mydict = {'x': x, 'y': y}
filename = '../data/test2.params'
nd.save(filename, mydict)
c = nd.load(filename)
print(c)

{'x': 
[ 1.  1.  1.]
<NDArray 3 @cpu(0)>, 'y': 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>}


#### 读取Gluon模型的参数
nn.Block提供了save_params和load_params函数来读写模型参数

In [5]:
def get_net():
    net = nn.Sequential()
    with net.name_scope():
        net.add(nn.Dense(10, activation='relu'))
        net.add(nn.Dense(2))
    return net

net = get_net()
net.initialize()
x = nd.random.uniform(shape=(2, 10))
print(net(x))


[[ 0.00202203  0.00100273]
 [-0.00134863  0.00299659]]
<NDArray 2x2 @cpu(0)>


In [6]:
# 存储模型的参数
filename = '../data/mlp.params'
net.save_params(filename)

In [7]:
# 读取net的模型参数，创建新模型net2
import mxnet as mx
net2 = get_net()
net2.load_params(filename, mx.cpu(0))
print(net2(x))


[[ 0.00202203  0.00100273]
 [-0.00134863  0.00299659]]
<NDArray 2x2 @cpu(0)>
